version: "3"
services:
  bruinen-backend:
    platform: linux/amd64
    image: bruinen-backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    # For localhost connection
    # Edit /etc/hosts and add 127.0.0.1	kubernetes.docker.internal
    # extra_hosts:
    #   - "kubernetes.docker.internal:host-gateway"
  bruinen-frontend:
    image: bruinen-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    restart: always
  postgres:
    image: postgres:15
    container_name: backend-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
