version: "3"
services:
  bruinen-backend:
    platform: linux/amd64
    build:
      context: ./backend/
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    # For localhost connection
    # Edit /etc/hosts and add 127.0.0.1	kubernetes.docker.internal
    # extra_hosts:
    #   - "kubernetes.docker.internal:host-gateway"
  bruinen-frontend:
    build:
      context: ./frontend/
      dockerfile: prod.Dockerfile
    ports:
      - "8000:3000"
    env_file:
      - ./frontend/.env
  postgres:
    image: postgres:15
    container_name: backend-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
