previewsEnabled: true
services:
  - type: web
    name: backend
    runtime: docker
    rootDir: backend
    dockerfilePath: prod.Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-staging
          property: connectionString
  - type: web
    runtime: node
    name: frontend
    rootDir: frontend
    buildCommand: "yarn && yarn build"
    startCommand: "yarn start"
    envVars:
      - key: NEXT_PUBLIC_ONTOLOGY_BACKEND
        fromService:
          type: web
          name: backend
          envVarKey: RENDER_EXTERNAL_URL
      - fromGroup: staging-frontend
databases:
  - name: db-staging
